version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
  sysdig-inspect:
    image: sysdiglabs/sysdig-inspect:0.1
    ports:
      - 3000:3000
    volumes:
      - ./captures:/captures
